---
abstract: 'Dispatcher module for command line interface programs'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
distribution_type: module
generated_by: 'Module::Install version 0.79'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-CLI
no_index:
  directory:
    - inc
    - t
requires:
  Getopt::Long: 2.35
  Locale::Maketext::Simple: 0
  Pod::Simple::Text: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
