---
abstract: 'Dispatcher module for command line interface programs'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
  - 'Yo-An Lin      <cornelius.howl@gmail.com>'
  - 'Shelling       <navyblueshellingford@gmail.com>'
  - 'Paul Cochrane  <paul@liekut.de>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Kwalitee: '0'
  Test::More: '0'
  Test::Pod: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-CLI
no_index:
  directory:
    - t
    - inc
requires:
  Capture::Tiny: '0'
  Carp: '0'
  Class::Load: '0'
  File::Basename: '0'
  File::Find: '0'
  Getopt::Long: '2.35'
  Locale::Maketext::Simple: '0'
  Pod::Simple::Text: '0'
  Scalar::Util: '0'
  base: '0'
  constant: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  repository: https://github.com/paultcochrane/app-cli
version: '0.47'
x_contributors:
  - 'José Joaquín Atria <jjatria@gmail.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
