name: App-CLI
version: 0.01
abstract: Dispatcher module for command line interface programs
author: Chia-liang Kao <clkao@clkao.org>
license: perl
distribution_type: module
requires:
  Getopt::Long: 2.34
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
