---
abstract: 'Dispatcher module for command line interface programs'
author:
  - 'Chia-liang Kao <clkao@clkao.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.28, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-CLI
no_index:
  directory:
    - t
    - inc
provides:
  App::CLI:
    file: lib/App/CLI.pm
  App::CLI::Command:
    file: lib/App/CLI/Command.pm
  App::CLI::Command::Help:
    file: lib/App/CLI/Command/Help.pm
  App::CLI::Helper:
    file: lib/App/CLI/Helper.pm
requires:
  Carp: '0'
  File::Find: '0'
  Getopt::Long: '2.35'
  Locale::Maketext::Simple: '0'
  Pod::Simple::Text: '0'
  perl: '5.006'
resources:
  repository: https://github.com/paultcochrane/app-cli
version: v0.4.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.012'
